---
#########################################
# Logical networks
#########################################
- name: Add networks
  ovirt_network:
    auth: "{{ ovirt_auth }}"
    state: "{{ item.state | default(omit) }}"
    name: "{{ item.name }}"
    data_center: "{{ data_center_name }}"
    vlan_tag: "{{ item.vlan_tag | default(omit) }}"
    vm_network: "{{ item.vm_network | default(omit) }}"
    mtu: "{{ item.mtu | default(omit) }}"
    description: "{{ item.description | default(omit) }}"
    clusters: "{{ item.clusters | default(omit) }}"
  with_items:
    - "{{ logical_networks | default([]) }}"
  tags:
    - logical_networks
    - networks
